"""Finalização do Banco

Revision ID: 2af37bef50ee
Revises: 00ae23443a39
Create Date: 2026-06-20 18:31:32.000455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af37bef50ee'
down_revision: Union[str, Sequence[str], None] = '00ae23443a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pergunta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('pergunta', sa.String(length=2000), nullable=False),
    sa.Column('alternativas', sa.JSON(), nullable=True),
    sa.Column('resposta', sa.String(length=1), nullable=True),
    sa.Column('feedback', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['Categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Registro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('acerto_categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['Categoria.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Usuario', sa.Column('acerto_total', sa.Integer(), nullable=True))
    op.add_column('Usuario', sa.Column('erro_total', sa.Integer(), nullable=True))
    op.alter_column('Usuario', 'senha',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_unique_constraint(None, 'Usuario', ['nome'])
    op.drop_column('Usuario', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Usuario', type_='unique')
    op.alter_column('Usuario', 'senha',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('Usuario', 'erro_total')
    op.drop_column('Usuario', 'acerto_total')
    op.drop_table('Registro')
    op.drop_table('Pergunta')
    op.drop_table('Categoria')
    # ### end Alembic commands ###
